== Naming conventions

Problem:: We don't have naming conventions for "42ity" project.
Solution:: Define them. 

=== What should naming convention cover:

 . github repository name
 . package naming scheme
 . library name
 . implementation files
 . C functions (prefix of exported functions/API)
 . daemon name
 . cli tool(s) name
 . config files
 . manpages and documentation
 . path names
 . can spill over to systemd unit names (services, timers, etc.) - although several units may be defined for different deliverables of the same source-code repo (e.g. both an agent or server and some house-keeping timer)

=== What naming convention does NOT cover:
All IPC product specific are out of scope (ipc-data, ipc-lcd-engine, ipc-meta)

=== Winning proposal

. github repository name 
. package naming scheme 
+
[options="header"]
|=======================================================================================
| Current repository name | New repository / package name
| agent-asset | fty-asset 
| agent-cm | fty-metric-compute 
| agent-metric-store | fty-metric-store 
| agent-nut | fty-nut 
| agent-outage | fty-outage 
| agent-rt | fty-metric-cache 
| agent-smtp | fty-email 
| agent-th | fty-sensor-env 
| agent-tpower | fty-metric-tpower 
| alert-agent | fty-alert-engine 
| alerts-list | fty-alert-list 
| composite-metrics | fty-metric-composite 
| core | fty-core 
| libbiosproto | fty-proto 
| kpi-uptime | NO DECISION YET
|=======================================================================================
+
proposals for kpi-uptime:
+
 * fty-uptime
 * fty-kpi-uptime
 * fty-kpi
 * fty-kpi-pwr-uptime
 * fty-indicator
 * fty-indicator-uptime
 * fty-power-uptime
. library name
. implementation files
. C functions (prefix of exported functions/API)
. daemon name
. cli tool(s) name
. config files
. manpages and documentation
. path names
. can spill over to systemd
+
Given the defined prefix ++fty++, points 3. - 11. are left up to the developers to deciide at run-time in minor details like i.e. dash vs underscore, etc ... even though there is a recommendation for it:
 * binaries (daemons / libraries / CLI and related manpages / config files) should use the dash
 * implementation files / functions / classes / structures should use the underscore


=== Winning proposal rationale

**FTY** is a shortcut of 42ity, which is short and can be used as C identifier.

Example repo::
+
----
    tree example.git/src/
    example.git/src/
    ├── fty_example_classes.h
    ├── fty_example_selftest
    ├── fty_example_selftest.c
    ├── fty-example
    ├── fty_example.c
    ├── fty-example.cfg.in
    ├── fty-example.service.in
    ├── fty_example_server.c
    ├── libfty_example.la
    └── libfty_example.pc.in
----

C function names::
+
----
    fty_proto_t *msg = fty_proto_new ();
    zactor_t *server = zactor_new (fty_rt_server, NULL);
    zmsg_t *msg = fty_smtp_encode (uuid, to, subject, body, NULL);
----    


